create database finalpro
use finalpro

create table department(d_id int ,d_medical varchar(20),d_csit varchar(20), d_mcomuni varchar(20),d_aviation varchar(20))
insert into department values(01,'','','','')
insert into department values(02,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
insert into department values(,'','','','')
select *from department

create table faculty(f_ids int , f_teachername varchar(20),f_teacherroonno varchar(20), f_teacherage int,f_contno int,)
insert into faculty values(01,'Manan','10',25,03002132422)
insert into faculty values(02,'Atif','11',26,030021323242)
insert into faculty values(03,'Amir','12',26,030021334532)
insert into faculty values(04,'Ateeq','13',27,03002135632)
insert into faculty values(05,'Ali','14',28, 0300213245652)
insert into faculty values(06,'Aslam','15',29,0300213218322)
insert into faculty values(07,'Fakhar','16',30,030021323452)
insert into faculty values(08,'Moazam','17',30,03003453452)
insert into faculty values(09,'Hafeez','18',31,030034543532)
insert into faculty values(10,'Ajmal','19',32,030021321832)
select *from faculty

create table students(s_id int , s_fname varchar(20),s_lname varchar(20),s_add varchar(20),s_email varchar(20),s_roolno varchar(20),s_rollno varchar(20))
insert into students values(01,'Ali','Amir','Lahore','Ali@gmail.com','2','Bcsm-f17-050')
insert into students values(02,'Atif','Ali','Karachi','Atif@gmail.com','4','Bcsm-f17-060')
insert into students values(03,'Amir','Ahmad','Lahore','Amir@gmail.com','5','Bcsm-f17-070')
insert into students values(04,'Tahir','Ali','Karachi','Tahir@gmail.com','6','Bcsm-f17-080')
insert into students values(05,'Tariq','Asim','Quetta','Tariq@gmail.com','7','Bcsm-f17-075')
insert into students values(06,'Yasir','Asif','Multan','Yasir@gmail.com','8','Bcsm-f17-095')
insert into students values(07,'Khizar','Hafeez','Karachi','Khizar@gmail.com','3','Bcsm-f17-052')
insert into students values(08,'Akmal','Fakhar','Peshawar','Akmal@gmail.com','4','Bcsm-f17-053')
insert into students values(09,'Amjad','Amir','Islamabad','Amjad@gmail.com','10','Bcsm-f17-067')
insert into students values(10,'Asad','Ajmal','Lahore','Asad@gmail.com','12','Bcsm-f17-078')
select *from students

create table std_marks(s_id int ,s_rollno varchar(20),s_subject varchar(20),s_sgpa decimal(15,3),s_cgpa decimal(15,3))
insert into std_marks values(01,'Bcsm-f17-050','OOP',3.4,3.2)
insert into std_marks values(02,'Bcsm-f17-060','DSA',3.1,3.0)
insert into std_marks values(03,'Bcsm-f17-080','CALCULAS',3.2,3.0)
insert into std_marks values(04,'Bcsm-f17-071','DISCRETE MATH',3.5,3.44)
insert into std_marks values(05,'Bcsm-f17-070','JAVA',2.5,2.89)
insert into std_marks values(06,'Bcsm-f17-078','PF',2.6,2.90)
insert into std_marks values(07,'Bcsm-f17-067','LINEAR',2.67,3.77)
insert into std_marks values(08,'Bcsm-f17-052','C_SKILL',2.8,3.55)
insert into std_marks values(09,'Bcsm-f17-050','CA',2.9,3.38)
insert into std_marks values(10,'Bcsm-f17-095','MARKETING',3.0,3.70)
select *from std_marks

create table std_attendence(s_fname varchar(20),s_lname varchar(20),s_roolno varchar(20),s_subjects varchar(20))
insert into std_attendence values('Ali','','','')
insert into std_attendence values('Atif','','','')
insert into std_attendence values('Asif','','','')
insert into std_attendence values('Amjad','','','')
insert into std_attendence values('Yasir','','','')
insert into std_attendence values('Ahmad','','','')
insert into std_attendence values('Amir','','','')
insert into std_attendence values('Hafeez','','','')
insert into std_attendence values('Asad','','','')
insert into std_attendence values('Khizar','','','') 
select *from std_attendence

create table teacher(t_id int , t_fname varchar(20),t_lname varchar(20), t_address varchar(20),t_email varchar(20))
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
insert into teacher values(,'','','','')
select *from teacher

create table voucher(v_id int , v_fname varchar(20),v_lname varchar(20), v_roolno varchar(20),v_firstins int, v_secondins int)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
insert into voucher values(,'','','',,)
select *from voucher

create table smester(s_id int , s_subname varchar(20),s_roonno varchar(20), s_teachername varchar(20),s_classday varchar(20), s_classtime int)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
insert into smester values(,'','','','',)
select *from smester

create table section(s_ids int , s_subjects varchar(20),s_roonno varchar(20), s_timing int,s_marks int)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
insert into section values(,'','',,)
select *from section

create table date_sheet(course_name varchar(20),section_name varchar(20),start_time int, end_time int,exame_date date) 
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
insert into date_sheet values('','',,,'')
select *from date_sheet